services:
  # A Docker web service
  - type: web
    name: instro-backend
    runtime: docker
    dockerfilePath: ./docker/instro.Dockerfile
    repo: https://github.com/InstroAISolutions/langflow
    branch: main
    plan: standard
    region: frankfurt
    healthCheckPath: /health_check
    autoDeploy: false
    envVars:
      - key: LANGFLOW_DATABASE_URL
        value: # db conenction string here e.g. postgresql://[db-user]:[db-password]@[server-url]:[port]/[db-name]
      - key: LANGFLOW_HOST
        value: 0.0.0.0
      - key: LANGFLOW_PORT
        value: 10000
      - key: LANGFLOW_LOG_LEVEL
        value: ERROR
      - key: LANGFLOW_SUPERUSER
        value: # username here
      - key: LANGFLOW_SUPERUSER_PASSWORD
        value: # password here           
      - key: LANGFLOW_AUTO_LOGIN
        value: false
