services:
  # A Docker web service
  - type: web
    name: langflow
    runtime: docker
    dockerfilePath: ./docker/render.Dockerfile
    repo: https://github.com/InstroAISolutions/langflow
    branch: main
    plan: standard
    healthCheckPath: /health_check
    autoDeploy: false
    envVars:
      - key: LANGFLOW_DATABASE_URL
        value: postgresql://langflow_poc_user:YoLhFJPzK5WJUJmv5HXg7GUf58iyWu9h@dpg-csrngj1u0jms7393biv0-a/langflow_poc
      - key: LANGFLOW_HOST
        value: 0.0.0.0
      - key: LANGFLOW_PORT
        # default render port https://docs.render.com/web-services#port-binding
        value: 10000
      - key: LANGFLOW_LOG_LEVEL
        value: INFO
      - key: LANGFLOW_SUPERUSER
        value: instro
      - key: LANGFLOW_SUPERUSER_PASSWORD
        value: 6p^m8jh5Z-Zjfu        